# Generated by Django 5.2.1 on 2025-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coder_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder_id', models.IntegerField()),
                ('coder_name', models.CharField(max_length=111)),
                ('coder_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
